#!/usr/bin/env bash
# Script that installs Nginx and configure it
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
service nginx start