#!/usr/bin/env bash
# This script displays Holberton School 10 times and Hi in 9th iteration,
x=0
while [ $x -le 9 ]
do
    if [ $x == 9 ]
    then
        echo 'Hi'
    fi
    echo 'Holberton School'
    ((x++))
done
