#!/usr/bin/env bash
# installing fire wall and setting port and some rules
sudo apt install ufw 
sudo ufw default deny incoming 
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw enable